version: '3.8'

services:
  build_aws_hipaa_services_list:
    container_name: "build_aws_hipaa_services_list"
    build:
      context: .
      dockerfile: ./Dockerfile
      target: dev
    environment:
      NODE_ENV: development
    env_file:
      - .env
    ports:
      - 9229:9229 # for node debug
    command: ["npm", "run", "dev"]
